#! /bin/bash
dump() {
	echo "//global functions" of "$1" ":" >>expr.h
	./decdump < "$1" >>expr.h
	echo "//global externs of" "$1" ":" >>expr.h
	./extdump < "$1" >>expr.h
}
cat expr.1.h > expr.h
dump expr-alloc.c
dump expr-buffered.c
dump expr-builtin.c
dump expr-core.c
dump expr-format.c
dump expr-global.c
dump expr-internal.c
echo "#if !(defined(EXPR_INLIB)&&(EXPR_INLIB))" >>expr.h
./rudump-mf >>expr.h
echo "#endif" >>expr.h
cat expr.2.h >> expr.h
